# mysql/tasks/main.yml
---

# Create Database if needed

  - name: Mysql Databases to be created
    debug: var=mysql_databases
    when: mysql_databases is defined

  - name: Create databases
    mysql_db: name="{{ item.db_schema }}" state=present login_user="root" login_password="{{ mysql_root_password }}"
    with_items: "{{ mysql_databases }}"
    when: mysql_databases is defined

  - name: Create database user and grant privileges
    mysql_user:
      name: "{{ item.db_user }}"
      password: "{{ item.db_password }}"
      host: "{{ item.db_user_host | default('%') }}"
      priv: "{{ item.db_user_priv | default(item.db_schema +'.*:ALL,GRANT') }}"
      state: present
      login_user: "root"
      login_password: "{{ mysql_root_password }}"
    with_items: "{{ mysql_databases }}"
    when: mysql_databases is defined

  - name: Create other users and grant privileges
    mysql_user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      host: "{{ item.host }}"
      priv: "{{ item.priv }}"
      state: present
      login_user: "root"
      login_password: "{{ mysql_root_password }}"
    with_items: "{{ mysql_users }}"