# mysql/tasks/main.yml
---

  - name: Add mysql 5.6 unofficial ppa for Ubuntu xenial
    apt_repository: repo='{{ item }}' state=present
    with_items:
      - "ppa:ondrej/mysql-5.6"
    when: ansible_distribution_release == "xenial" and mysql_version == "mysql-server-5.6"

  - name: General | Install required packages.
    action: apt pkg={{ item }} state=installed update_cache=yes
    with_items:
      - "{{ mysql_version | default('mysql-server') }}"
      # plugin python necessaire pour creer les databases
      - python-mysqldb

  - name: MySQL | Configuration file, my.cnf
    template: src=etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf force=yes
    notify: restart mysql