# mysql/tasks/main.yml
---

  - include: install_mysql.yml
    when: not mysql_skip_install
    tags: mysql_install

  - include: mysql_secure.yml
    tags:
      - mysql_install
      - mysql_secure

  - include: databases.yml
    when: mysql_databases is defined or mysql_users is defined
    tags: mysql_restore_db

  - include: restore_dump.yml
    when: mysql_databases is defined and not mysql_skip_dump
    tags: mysql_restore_db